Change the depreacted sprintf to snprintf with the extra buffer size param
[54/157] Building CXX object IOConnector/CMakeFiles/ThunderIOConnector.dir/GPIO.cpp.o
FAILED: IOConnector/CMakeFiles/ThunderIOConnector.dir/GPIO.cpp.o 
/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DPROCESSCONTAINERS_ENABLED=1 -DTHUNDER_PLATFORM_PC_UNIX=1 -DThunderIOConnector_EXPORTS -DWARNING_REPORTING_ENABLED -D_TRACE_LEVEL=0 -D__CORE_MESSAGING__ -D__CORE_NO_WCHAR_SUPPORT__ -D__CORE_WARNING_REPORTING__ -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Debug/install/usr/include/Thunder -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Debug/install/usr/include -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Debug/install/usr/include/Thunder/processcontainers -Wall -Wextra -Wpedantic -Werror -g -std=gnu++11 -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -O0 -g -MD -MT IOConnector/CMakeFiles/ThunderIOConnector.dir/GPIO.cpp.o -MF IOConnector/CMakeFiles/ThunderIOConnector.dir/GPIO.cpp.o.d -o IOConnector/CMakeFiles/ThunderIOConnector.dir/GPIO.cpp.o -c /Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/IOConnector/GPIO.cpp
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/IOConnector/GPIO.cpp:73:13: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
            sprintf(buffer, "/sys/class/gpio/gpio%d/value", _pin);
            ^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/stdio.h:180:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/sys/cdefs.h:218:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))