Try to make DHCPClient work on MacOS since some constants are not recognized
 [63/157] Building CXX object NetworkControl/CMakeFiles/ThunderNetworkControl.dir/DHCPClient.cpp.o
FAILED: NetworkControl/CMakeFiles/ThunderNetworkControl.dir/DHCPClient.cpp.o 
/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DPROCESSCONTAINERS_ENABLED=1 -DTHUNDER_PLATFORM_PC_UNIX=1 -DThunderNetworkControl_EXPORTS -DWARNING_REPORTING_ENABLED -D_TRACE_LEVEL=0 -D__CORE_MESSAGING__ -D__CORE_NO_WCHAR_SUPPORT__ -D__CORE_WARNING_REPORTING__ -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Debug/install/usr/include/Thunder -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Debug/install/usr/include -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Debug/install/usr/include/Thunder/processcontainers -Wall -Wextra -Wpedantic -Werror -g -std=gnu++11 -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -O0 -g -MD -MT NetworkControl/CMakeFiles/ThunderNetworkControl.dir/DHCPClient.cpp.o -MF NetworkControl/CMakeFiles/ThunderNetworkControl.dir/DHCPClient.cpp.o.d -o NetworkControl/CMakeFiles/ThunderNetworkControl.dir/DHCPClient.cpp.o -c /Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/NetworkControl/DHCPClient.cpp
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/NetworkControl/DHCPClient.cpp:39:49: error: use of undeclared identifier 'ETH_P_IP'
            Core::NodeId(interfaceName.c_str(), ETH_P_IP, PACKET_BROADCAST, 0, sizeof(BroadcastMAC), BroadcastMAC),
                                                ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/NetworkControl/DHCPClient.cpp:39:59: error: use of undeclared identifier 'PACKET_BROADCAST'
            Core::NodeId(interfaceName.c_str(), ETH_P_IP, PACKET_BROADCAST, 0, sizeof(BroadcastMAC), BroadcastMAC),
                                                          ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/NetworkControl/DHCPClient.cpp:40:49: error: use of undeclared identifier 'ETH_P_IP'
            Core::NodeId(interfaceName.c_str(), ETH_P_IP, PACKET_BROADCAST, 0, sizeof(BroadcastMAC), BroadcastMAC),
                                                ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/NetworkControl/DHCPClient.cpp:40:59: error: use of undeclared identifier 'PACKET_BROADCAST'
            Core::NodeId(interfaceName.c_str(), ETH_P_IP, PACKET_BROADCAST, 0, sizeof(BroadcastMAC), BroadcastMAC),
                                                          ^
4 errors generated.