Add some missing overrides and remove unnecessary member
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/examples/OutOfProcessPlugin/OutOfProcessImplementation.cpp:486:22: error: 'Unregister' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual void Unregister(Exchange::IBrowser::INotification* sink)
                     ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/Release/install/usr/include/Thunder/interfaces/IBrowser.h:45:22: note: overridden virtual function is here
        virtual void Unregister(IBrowser::INotification* sink) = 0;
                     ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/examples/OutOfProcessPlugin/OutOfProcessImplementation.cpp:713:26: error: 'Worker' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual uint32_t Worker()
                         ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/Release/install/usr/include/Thunder/core/Thread.h:242:26: note: overridden virtual function is here
        virtual uint32_t Worker() = 0;
                         ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/examples/OutOfProcessPlugin/OutOfProcessImplementation.cpp:814:26: error: 'Resident' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual uint64_t Resident() const
                         ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/Release/install/usr/include/Thunder/interfaces/IMemory.h:35:26: note: overridden virtual function is here
        virtual uint64_t Resident() const = 0;
                         ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/examples/OutOfProcessPlugin/OutOfProcessImplementation.cpp:818:26: error: 'Allocated' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual uint64_t Allocated() const
                         ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/Release/install/usr/include/Thunder/interfaces/IMemory.h:36:26: note: overridden virtual function is here
        virtual uint64_t Allocated() const = 0;
                         ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/examples/OutOfProcessPlugin/OutOfProcessImplementation.cpp:822:26: error: 'Shared' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual uint64_t Shared() const
                         ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/Release/install/usr/include/Thunder/interfaces/IMemory.h:37:26: note: overridden virtual function is here
        virtual uint64_t Shared() const = 0;
                         ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/examples/OutOfProcessPlugin/OutOfProcessImplementation.cpp:826:25: error: 'Processes' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual uint8_t Processes() const
                        ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/Release/install/usr/include/Thunder/interfaces/IMemory.h:38:25: note: overridden virtual function is here
        virtual uint8_t Processes() const = 0;
                        ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/examples/OutOfProcessPlugin/OutOfProcessImplementation.cpp:830:22: error: 'IsOperational' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
        virtual bool IsOperational() const
                     ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/Release/install/usr/include/Thunder/interfaces/IMemory.h:39:22: note: overridden virtual function is here
        virtual bool IsOperational() const = 0;
                     ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/examples/OutOfProcessPlugin/OutOfProcessImplementation.cpp:137:41: error: private field '_parent' is not used [-Werror,-Wunused-private-field]
            OutOfProcessImplementation& _parent;
                                        ^
10 errors generated.