Disabling WebShell which is Linux specific
 /Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/WebShell/WebShell.cpp:291:25: error: use of undeclared identifier 'signalfd'
            _signalFD = signalfd(-1, &sigset, 0);
                        ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/WebShell/WebShell.cpp:361:45: error: variable has incomplete type 'struct signalfd_siginfo'
                    struct signalfd_siginfo info;
                                            ^
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/WebShell/WebShell.cpp:361:28: note: forward declaration of 'signalfd_siginfo'
                    struct signalfd_siginfo info;
                           ^
3 errors generated.