Disabling CECControl from building due to undefined arm64 symbols
FAILED: CECControl/libThunderCECControl.dylib 
: && /Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -Wall -Wextra -Wpedantic -Werror -Os -DNDEBUG -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -dynamiclib -Wl,-headerpad_max_install_names  -o CECControl/libThunderCECControl.dylib -install_name @rpath/libThunderCECControl.dylib CECControl/CMakeFiles/ThunderCECControl.dir/CECControl.cpp.o CECControl/CMakeFiles/ThunderCECControl.dir/Module.cpp.o CECControl/CMakeFiles/ThunderCECControl.dir/adapter/processor/messages/MenuLanguage.cpp.o CECControl/CMakeFiles/ThunderCECControl.dir/adapter/processor/messages/OSDName.cpp.o CECControl/CMakeFiles/ThunderCECControl.dir/adapter/processor/messages/OSDString.cpp.o CECControl/CMakeFiles/ThunderCECControl.dir/adapter/processor/messages/PhysicalAddress.cpp.o CECControl/CMakeFiles/ThunderCECControl.dir/adapter/processor/messages/SetStreamPath.cpp.o CECControl/CMakeFiles/ThunderCECControl.dir/adapter/processor/messages/Standby.cpp.o CECControl/CMakeFiles/ThunderCECControl.dir/adapter/processor/messages/VendorID.cpp.o CECControl/CMakeFiles/ThunderCECControl.dir/adapter/processor/messages/Version.cpp.o  -Wl,-rpath,/Users/runner/work/ThunderNanoServices/ThunderNanoServices/MinSizeRel/install/usr/lib  CECControl/adapter/lib_cecadapter.a  /Users/runner/work/ThunderNanoServices/ThunderNanoServices/MinSizeRel/install/usr/lib/libThunderPlugins.5.0.0.dylib  /Users/runner/work/ThunderNanoServices/ThunderNanoServices/MinSizeRel/install/usr/lib/libThunderDefinitions.5.0.0.dylib  CECControl/adapter/device_adapter/lib_ceccontrol_device_adapter.a  CECControl/adapter/processor/lib_cec_message_processor.a  /Users/runner/work/ThunderNanoServices/ThunderNanoServices/MinSizeRel/install/usr/lib/libThunderCOM.5.0.0.dylib  /Users/runner/work/ThunderNanoServices/ThunderNanoServices/MinSizeRel/install/usr/lib/libThunderProcessContainers.5.0.0.dylib  /Users/runner/work/ThunderNanoServices/ThunderNanoServices/MinSizeRel/install/usr/lib/libThunderWebSocket.5.0.0.dylib  /Users/runner/work/ThunderNanoServices/ThunderNanoServices/MinSizeRel/install/usr/lib/libThunderCryptalgo.5.0.0.dylib  /Users/runner/work/ThunderNanoServices/ThunderNanoServices/MinSizeRel/install/usr/lib/libThunderWarningReporting.5.0.0.dylib  /Users/runner/work/ThunderNanoServices/ThunderNanoServices/MinSizeRel/install/usr/lib/libThunderMessaging.5.0.0.dylib  /Users/runner/work/ThunderNanoServices/ThunderNanoServices/MinSizeRel/install/usr/lib/libThunderCore.5.0.0.dylib && :
Undefined symbols for architecture arm64:
  "_cec_adapter_claim_role", referenced from:
      Thunder::CEC::CECAccessor::AdapterImplementation::AdapterImplementation(Thunder::CEC::CECAccessor::Config const&) in lib_cecadapter.a[5](CECAccessor.cpp.o)
  "_cec_adapter_create", referenced from:
      Thunder::CEC::CECAccessor::AdapterImplementation::AdapterImplementation(Thunder::CEC::CECAccessor::Config const&) in lib_cecadapter.a[5](CECAccessor.cpp.o)
  "_cec_adapter_destroy", referenced from:
      Thunder::CEC::CECAccessor::AdapterImplementation::~AdapterImplementation() in lib_cecadapter.a[5](CECAccessor.cpp.o)
  "_cec_adapter_receive", referenced from:
      Thunder::CEC::CECAccessor::AdapterImplementation::AdapterImplementation(Thunder::CEC::CECAccessor::Config const&) in lib_cecadapter.a[5](CECAccessor.cpp.o)
      Thunder::CEC::CECAccessor::AdapterImplementation::~AdapterImplementation() in lib_cecadapter.a[5](CECAccessor.cpp.o)
  "_cec_adapter_release_role", referenced from:
      Thunder::CEC::CECAccessor::AdapterImplementation::~AdapterImplementation() in lib_cecadapter.a[5](CECAccessor.cpp.o)
  "_cec_adapter_transmit", referenced from:
      Thunder::CEC::CECAccessor::AdapterImplementation::Transmit(cec_adapter_role, Thunder::CEC::logical_address_type, unsigned char, unsigned char const*) in lib_cecadapter.a[5](CECAccessor.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)