No need for self-assignment check since ConfigData pointer will be different from ConfigInfo one
[72/145] Building CXX object WifiControl/CMakeFiles/ThunderWifiControl.dir/WifiControlImplementation.cpp.o
FAILED: WifiControl/CMakeFiles/ThunderWifiControl.dir/WifiControlImplementation.cpp.o 
/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DPROCESSCONTAINERS_ENABLED=1 -DTHUNDER_PLATFORM_PC_UNIX=1 -DThunderWifiControl_EXPORTS -DWARNING_REPORTING_ENABLED -D_TRACE_LEVEL=0 -D__CORE_MESSAGING__ -D__CORE_NO_WCHAR_SUPPORT__ -D__CORE_WARNING_REPORTING__ -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Release/install/usr/include/Thunder -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Release/install/usr/include -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Release/install/usr/include/Thunder/processcontainers -Wall -Wextra -Wpedantic -Werror -O3 -DNDEBUG -std=gnu++11 -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wno-psabi -MD -MT WifiControl/CMakeFiles/ThunderWifiControl.dir/WifiControlImplementation.cpp.o -MF WifiControl/CMakeFiles/ThunderWifiControl.dir/WifiControlImplementation.cpp.o.d -o WifiControl/CMakeFiles/ThunderWifiControl.dir/WifiControlImplementation.cpp.o -c /Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/WifiControl/WifiControlImplementation.cpp
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/WifiControl/WifiControlImplementation.cpp:683:26: error: comparison of distinct pointer types ('Thunder::Plugin::WifiControlImplementation::ConfigData *' and 'const ConfigInfo *')
                if (this != &rhs) {
                    ~~~~ ^  ~~~~
1 error generated.