Remove the unused _announceHandler
[78/145] Building CXX object examples/COMRPCClient/CMakeFiles/COMRPCClient.dir/COMRPCClient.cpp.o
FAILED: examples/COMRPCClient/CMakeFiles/COMRPCClient.dir/COMRPCClient.cpp.o 
/Applications/Xcode_15.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DPROCESSCONTAINERS_ENABLED=1 -DTHUNDER_PLATFORM_PC_UNIX=1 -DWARNING_REPORTING_ENABLED -D_TRACE_LEVEL=0 -D__CORE_MESSAGING__ -D__CORE_NO_WCHAR_SUPPORT__ -D__CORE_WARNING_REPORTING__ -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Debug/install/usr/include/Thunder -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Debug/install/usr/include -isystem /Users/runner/work/ThunderNanoServices/ThunderNanoServices/Debug/install/usr/include/Thunder/processcontainers -Wall -Wextra -Wpedantic -Werror -g -std=gnu++11 -arch arm64 -isysroot /Applications/Xcode_15.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O0 -g -MD -MT examples/COMRPCClient/CMakeFiles/COMRPCClient.dir/COMRPCClient.cpp.o -MF examples/COMRPCClient/CMakeFiles/COMRPCClient.dir/COMRPCClient.cpp.o.d -o examples/COMRPCClient/CMakeFiles/COMRPCClient.dir/COMRPCClient.cpp.o -c /Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/examples/COMRPCClient/COMRPCClient.cpp
/Users/runner/work/ThunderNanoServices/ThunderNanoServices/ThunderNanoServices/examples/COMRPCClient/COMRPCClient.cpp:209:23: error: private field '_announceHandler' is not used [-Werror,-Wunused-private-field]
    Core::IIPCServer* _announceHandler;
                      ^
1 error generated.